"""
Sync curated channels from Supabase → ytdl-sub subscriptions.yaml

Usage:
    python scripts/sync_subscriptions.py

Reads curated channels from the PradoTube database and generates
ytdl-sub/subscriptions.yaml so ytdl-sub downloads match what's curated.
"""

import os
import sys
from pathlib import Path

try:
    from supabase import create_client
except ImportError:
    print("Missing dependency: pip install supabase")
    sys.exit(1)

try:
    import yaml
except ImportError:
    print("Missing dependency: pip install pyyaml")
    sys.exit(1)

# Load env from .env file in project root
PROJECT_ROOT = Path(__file__).resolve().parent.parent
ENV_FILE = PROJECT_ROOT / ".env"

def load_env():
    """Load .env file into os.environ (simple parser, no dependency needed)."""
    if not ENV_FILE.exists():
        return
    with open(ENV_FILE) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            os.environ.setdefault(key.strip(), value.strip())

def fetch_curated_channels(supabase_client):
    """Fetch curated channels joined with channel metadata."""
    response = (
        supabase_client.table("curated_channels")
        .select("channel_id, display_order, notes, channels(youtube_id, title, custom_url)")
        .order("display_order")
        .execute()
    )
    return response.data

def build_subscriptions(channels):
    """Build the subscriptions.yaml structure from curated channel data."""
    subs = {}
    for row in channels:
        channel = row.get("channels")
        if not channel:
            print(f"  Warning: curated_channels row {row['channel_id']} has no joined channel data, skipping")
            continue

        custom_url = channel.get("custom_url")

        if custom_url:
            # Use handle as key (e.g. "@funquesters") — becomes folder name
            key = custom_url
            url = f"https://www.youtube.com/{custom_url}"
        else:
            key = channel["youtube_id"]
            url = f"https://www.youtube.com/channel/{channel['youtube_id']}"

        subs[key] = url

    return {"PradoTube": subs}

def main():
    load_env()

    supabase_url = os.environ.get("NEXT_PUBLIC_SUPABASE_URL")
    supabase_key = os.environ.get("SUPABASE_SECRET_KEY")

    if not supabase_url or not supabase_key:
        print("Error: NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SECRET_KEY must be set")
        sys.exit(1)

    client = create_client(supabase_url, supabase_key)

    print("Fetching curated channels from Supabase...")
    channels = fetch_curated_channels(client)
    print(f"  Found {len(channels)} curated channel(s)")

    if not channels:
        print("  No curated channels found. Nothing to sync.")
        return

    subscriptions = build_subscriptions(channels)

    output_path = PROJECT_ROOT / "ytdl-sub" / "subscriptions.yaml"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by sync_subscriptions.py — do not edit manually\n")
        f.write(f"# Synced {len(channels)} curated channel(s) from Supabase\n\n")
        yaml.dump(subscriptions, f, default_flow_style=False, allow_unicode=True, sort_keys=False)

    print(f"  Written to {output_path}")
    print("\nRun ytdl-sub:")
    print(f"  ytdl-sub sub --config ytdl-sub/config.yaml ytdl-sub/subscriptions.yaml")

if __name__ == "__main__":
    main()
