"""
Sync curated channels from Supabase → ytdl-sub subscriptions.yaml

Usage:
    python scripts/sync_subscriptions.py

Reads curated channels from the PradoTube database and generates
ytdl-sub/subscriptions.yaml so ytdl-sub downloads match what's curated.
"""

import os
import sys
from pathlib import Path

try:
    from supabase import create_client
except ImportError:
    print("Missing dependency: pip install supabase")
    sys.exit(1)


# Load env from .env file in project root
PROJECT_ROOT = Path(__file__).resolve().parent.parent
ENV_FILE = PROJECT_ROOT / ".env"

def load_env():
    """Load .env file into os.environ (simple parser, no dependency needed)."""
    if not ENV_FILE.exists():
        return
    with open(ENV_FILE) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            os.environ.setdefault(key.strip(), value.strip())

def fetch_curated_channels(supabase_client):
    """Fetch curated channels joined with channel metadata."""
    response = (
        supabase_client.table("curated_channels")
        .select("channel_id, display_order, notes, date_range_override, channels(youtube_id, title, custom_url)")
        .order("display_order")
        .execute()
    )
    return response.data

def build_subscriptions_yaml(channels):
    """Build subscriptions.yaml content as a string.

    Channels with date_range_override use ytdl-sub tilda (~) syntax
    to set per-subscription override variables.
    """
    regular = []   # (key, url)
    overrides = []  # (key, url, date_range_after)

    for row in channels:
        channel = row.get("channels")
        if not channel:
            print(f"  Warning: curated_channels row {row['channel_id']} has no joined channel data, skipping")
            continue

        custom_url = channel.get("custom_url")

        if custom_url:
            key = custom_url
            url = f"https://www.youtube.com/{custom_url}/videos"
        else:
            key = channel["youtube_id"]
            url = f"https://www.youtube.com/channel/{channel['youtube_id']}/videos"

        date_override = row.get("date_range_override")
        if date_override:
            overrides.append((key, url, date_override))
        else:
            regular.append((key, url))

    lines = ["PradoTube:"]

    # Regular channels: simple "key": "url" format
    for key, url in regular:
        lines.append(f"  '{key}': {url}")

    # Override channels: tilda (~) syntax with per-subscription variables
    if overrides:
        lines.append("")
        lines.append("  # Per-channel date range overrides (tilda syntax)")
        for key, url, date_after in overrides:
            lines.append(f"  '~{key}':")
            lines.append(f"    url: {url}")
            lines.append(f"    date_range_after: \"{date_after}\"")

    return "\n".join(lines) + "\n"

def main():
    load_env()

    supabase_url = os.environ.get("NEXT_PUBLIC_SUPABASE_URL")
    supabase_key = os.environ.get("SUPABASE_SECRET_KEY")

    if not supabase_url or not supabase_key:
        print("Error: NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SECRET_KEY must be set")
        sys.exit(1)

    client = create_client(supabase_url, supabase_key)

    print("Fetching curated channels from Supabase...")
    channels = fetch_curated_channels(client)
    print(f"  Found {len(channels)} curated channel(s)")

    if not channels:
        print("  No curated channels found. Nothing to sync.")
        return

    content = build_subscriptions_yaml(channels)

    output_path = PROJECT_ROOT / "ytdl-sub" / "subscriptions.yaml"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by sync_subscriptions.py — do not edit manually\n")
        f.write(f"# Synced {len(channels)} curated channel(s) from Supabase\n\n")
        f.write(content)

    print(f"  Written to {output_path}")
    print("\nRun ytdl-sub:")
    print(f"  ytdl-sub sub --config ytdl-sub/config.yaml ytdl-sub/subscriptions.yaml")

if __name__ == "__main__":
    main()
